services:
  email-service:
    build: .
    container_name: email-service
    restart: unless-stopped
    volumes:
      - ./templates:/app/templates  # Maps local templates folder to container

networks:
  npm-network:
    external: true